name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]  # Triggers on push and manual execution

env:
  RESOURCE_GROUP: eshoponweb-rg
  LOCATION: eastasia
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: 98c13e3f-ff9d-4f3f-a523-939b9f7de9a5
  WEBAPP_NAME: eshoponweb-webapp290

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'

    - name: Restore dependencies
      run: dotnet restore eShopOnWeb.sln

    - name: Build with dotnet
      run: dotnet build eShopOnWeb.sln --configuration Release

    - name: Test with dotnet
      run: dotnet test eShopOnWeb.sln --configuration Release

    - name: dotnet publish
      run: |
        export DOTNET_ROOT=${DOTNET_ROOT:-/home/runner/.dotnet}
        mkdir -p $DOTNET_ROOT/myapp
        dotnet publish ./src/Web/Web.csproj -c Release -o $DOTNET_ROOT/myapp
        cd $DOTNET_ROOT/myapp
        zip -r ../app.zip .

    - name: Debug - List Published Files
      run: ls -lah /home/runner/.dotnet/

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: /home/runner/.dotnet/app.zip
        retention-days: 10  # Increased retention period

    - name: Upload Bicep Template
      uses: actions/upload-artifact@v4
      with:
        name: bicep-template
        path: ${{ env.TEMPLATE_FILE }}
        retention-days: 10

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
    - name: List Available Artifacts
      run: ls -lah $GITHUB_WORKSPACE  # Check if artifacts exist

    - name: Download dotnet-app Artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app
        path: dotnet-app

    - name: Debug - List Downloaded Files
      run: ls -lah dotnet-app/

    - name: Download Bicep Template
      uses: actions/download-artifact@v4
      with:
        name: bicep-template
        path: bicep-template

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Infrastructure
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: bicep-template/webapp.bicep
        parameters: 'webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }}'
        failOnStdErr: false   

    - name: Publish Website to WebApp
      uses: Azure/cli@v2
      with:
        inlineScript: |
          az webapp deployment source config-zip --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.WEBAPP_NAME }} --src dotnet-app/app.zip
